# Jekyll configuration

title: The C++ Alliance
email: info@cppalliance.com
url: http://cppalliance.org # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: /subpath # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
  The C++ Alliance is dedicated to helping the C++ programming language
  evolve. We see it developing as an ecosystem of open source libraries
  and as a growing community of those who contribute to those libraries..
excerpt_separator: "<!-- more -->"
github_username: CPPAlliance
twitter:
  username: CPPAlliance
  card: summary
  site: '@CPPAlliance'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
